services:
  pylint:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: my-test-image
    command: bash -c "python -m pylint src"
    container_name: pylint-container
    env_file:
      - compose.env

  flake8:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: my-test-image
    command: bash -c "python -m flake8 src"
    container_name: flake8-container
    env_file:
      - compose.env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-project-image
    command: bash -c "
      python main.py execute --option ${MY_VAR}"
    container_name: app-container
    env_file:
      - compose.env
